services:
    namenode:
      image: apache/hadoop:3.4.1
      hostname: namenode
      user: root
      command: ["hdfs", "namenode"]
      ports:
        - 9870:9870
      environment:
        ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"
      volumes:
        - ./hadoop/shared:/opt/hadoop/input_files
      env_file:
        - ./config
      networks:
        - hdfs_network

    datanode_1:
      image: apache/hadoop:3.4.1
      command: ["hdfs", "datanode"]
      env_file:
        - ./config
      networks:
        - hdfs_network

    datanode_2:
      image: apache/hadoop:3.4.1
      command: ["hdfs", "datanode"]
      env_file:
        - ./config
      networks:
        - hdfs_network

    resourcemanager:
      image: apache/hadoop:3.4.1
      command: ["yarn", "resourcemanager"]
      ports:
        - 8088:8088
      env_file:
        - ./config
      networks:
        - hdfs_network

    nodemanager:
        image: apache/hadoop:3.4.1
        command: ["yarn", "nodemanager"]
        environment:
            ENSURE_NODEMANAGER_DIR: "tmp/hadoop-hadoop/nm-local-dir/"
        networks:
          - hdfs_network
        env_file:
          - ./config

volumes:
  datanode1:
  datanode2:
  namenode:

networks: 
    hdfs_network:
        # Specify driver options
        driver: bridge
        driver_opts:
            com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"
